version: "3.8"

services:
  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "5173:5173"   # Vite par défaut (ou 3000 pour CRA)
    stdin_open: true
    tty: true
